names:
- Algal_leave
- Leaf_rot
- Phomopsis
- Pink_Disease
- early_blight
- root_disease
- Anthracnose
nc: 7
roboflow:
  license: Private
  project: leave_disease-rvavl
  url: https://app.roboflow.com/limagriculture/leave_disease-rvavl/2
  version: 2
  workspace: limagriculture
test: ../test/images
train: C:/Users/Lim Ding Shan/Desktop/Durian project and paper/second paper/Leave_disease/train/images
val: C:/Users/Lim Ding Shan/Desktop/Durian project and paper/second paper/Leave_disease/valid/images
